MAID_WALLY_PATH: str
MIDAS_WALLY_PATH: str
GENERATED_HEADER_WARNING_COMMENT: str

def build_shared_luau_tree() -> None: ...
def build_client_boot() -> None: ...
def build_server_boot() -> None: ...
def main() -> None: ...
